"""
Generate 200 famous stock market indices for FinSight database.
Outputs Python list entries to append to generated_data.py
"""
import random
import json

random.seed(42)

# Top 200 famous world indices
INDICES = [
    # Indian Indices (1-50)
    ("NIFTY50", "Nifty 50", "NSE", "Index", "Broad Market", 22300),
    ("SENSEX", "BSE Sensex", "BSE", "Index", "Broad Market", 73500),
    ("NIFTYBANK", "Nifty Bank", "NSE", "Index", "Banking", 48200),
    ("NIFTYIT", "Nifty IT", "NSE", "Index", "Information Technology", 34500),
    ("NIFTYPHARMA", "Nifty Pharma", "NSE", "Index", "Pharma", 18200),
    ("NIFTYFMCG", "Nifty FMCG", "NSE", "Index", "FMCG", 55800),
    ("NIFTYAUTO", "Nifty Auto", "NSE", "Index", "Automobile", 23400),
    ("NIFTYMETAL", "Nifty Metal", "NSE", "Index", "Metals and Mining", 8900),
    ("NIFTYREALTY", "Nifty Realty", "NSE", "Index", "Real Estate", 1020),
    ("NIFTYMEDIA", "Nifty Media", "NSE", "Index", "Media", 2150),
    ("NIFTYENERGY", "Nifty Energy", "NSE", "Index", "Energy", 35800),
    ("NIFTYINFRA", "Nifty Infrastructure", "NSE", "Index", "Infrastructure", 6850),
    ("NIFTYPSE", "Nifty PSE", "NSE", "Index", "PSU", 8400),
    ("NIFTYPVTBANK", "Nifty Private Bank", "NSE", "Index", "Private Banking", 23500),
    ("NIFTYPSUBANK", "Nifty PSU Bank", "NSE", "Index", "PSU Banking", 6800),
    ("NIFTYFIN", "Nifty Financial Services", "NSE", "Index", "Financial Services", 20800),
    ("NIFTYFINEX", "Nifty Fin Services 25/50", "NSE", "Index", "Financial Services", 21200),
    ("NIFTY100", "Nifty 100", "NSE", "Index", "Broad Market", 22500),
    ("NIFTY200", "Nifty 200", "NSE", "Index", "Broad Market", 12400),
    ("NIFTY500", "Nifty 500", "NSE", "Index", "Broad Market", 20200),
    ("NIFTYNEXT50", "Nifty Next 50", "NSE", "Index", "Broad Market", 62500),
    ("NIFTYMIDCAP50", "Nifty Midcap 50", "NSE", "Index", "Midcap", 14800),
    ("NIFTYMID100", "Nifty Midcap 100", "NSE", "Index", "Midcap", 52400),
    ("NIFTYMID150", "Nifty Midcap 150", "NSE", "Index", "Midcap", 18500),
    ("NIFTYSML100", "Nifty Smallcap 100", "NSE", "Index", "Smallcap", 17200),
    ("NIFTYSML250", "Nifty Smallcap 250", "NSE", "Index", "Smallcap", 16800),
    ("NIFTYSML50", "Nifty Smallcap 50", "NSE", "Index", "Smallcap", 8400),
    ("NIFTYMICRO", "Nifty MicroCap 250", "NSE", "Index", "Microcap", 20500),
    ("NIFTYLARGEMID", "Nifty LargeMidcap 250", "NSE", "Index", "Broad Market", 15200),
    ("NIFTYCONSUM", "Nifty Consumer Durables", "NSE", "Index", "Consumer Durables", 32500),
    ("NIFTYCPSE", "Nifty CPSE", "NSE", "Index", "PSU", 5600),
    ("NIFTYDEFENCE", "Nifty India Defence", "NSE", "Index", "Defence", 6200),
    ("NIFTYTOURISM", "Nifty India Tourism", "NSE", "Index", "Tourism", 6800),
    ("NIFTYOILGAS", "Nifty Oil and Gas", "NSE", "Index", "Oil and Gas", 11800),
    ("NIFTYHEALTHCARE", "Nifty Healthcare", "NSE", "Index", "Healthcare", 12400),
    ("NIFTYMOBILITY", "Nifty Mobility", "NSE", "Index", "Automobile", 8900),
    ("NIFTYHOUSING", "Nifty Housing", "NSE", "Index", "Real Estate", 10200),
    ("NIFTYCONSUMER", "Nifty India Consumer", "NSE", "Index", "Consumer", 9800),
    ("NIFTYMNC", "Nifty MNC", "NSE", "Index", "Diversified", 26800),
    ("NIFTYDIVIDEND", "Nifty Dividend Opp 50", "NSE", "Index", "Dividend", 4800),
    ("NIFTYGROWTH", "Nifty Growth Sectors 15", "NSE", "Index", "Growth", 9200),
    ("NIFTYMOM30", "Nifty Alpha 50", "NSE", "Index", "Momentum", 42000),
    ("NIFTYEQUALWT", "Nifty 50 Equal Weight", "NSE", "Index", "Broad Market", 26500),
    ("NIFTYVAL20", "Nifty 50 Value 20", "NSE", "Index", "Value", 12200),
    ("NIFTYQUALY30", "Nifty Quality 30", "NSE", "Index", "Quality", 5100),
    ("NIFTYLOWVOL", "Nifty Low Volatility 50", "NSE", "Index", "Low Volatility", 18200),
    ("NIFTYHIGHBETA", "Nifty High Beta 50", "NSE", "Index", "High Beta", 3600),
    ("NIFTY100QUALY", "Nifty 100 Quality 30", "NSE", "Index", "Quality", 4800),
    ("BSE500", "BSE 500", "BSE", "Index", "Broad Market", 32500),
    ("BSEMIDCAP", "BSE MidCap", "BSE", "Index", "Midcap", 33800),
    # US Indices (51-90)
    ("SPX", "S&P 500", "NYSE", "Index", "Broad Market", 5200),
    ("DJI", "Dow Jones Industrial Average", "NYSE", "Index", "Blue Chip", 39800),
    ("IXIC", "NASDAQ Composite", "NASDAQ", "Index", "Technology", 16400),
    ("NDX", "NASDAQ-100", "NASDAQ", "Index", "Technology", 18200),
    ("RUT", "Russell 2000", "NYSE", "Index", "Small Cap", 2080),
    ("RUI", "Russell 1000", "NYSE", "Index", "Large Cap", 2950),
    ("RUA", "Russell 3000", "NYSE", "Index", "Broad Market", 3100),
    ("MID", "S&P MidCap 400", "NYSE", "Index", "Mid Cap", 2850),
    ("SML", "S&P SmallCap 600", "NYSE", "Index", "Small Cap", 1350),
    ("VIX", "CBOE Volatility Index", "CBOE", "Index", "Volatility", 15.2),
    ("SOX", "PHLX Semiconductor", "NASDAQ", "Index", "Semiconductors", 4800),
    ("KBW", "KBW Bank Index", "NASDAQ", "Index", "Banking", 112),
    ("XBI", "S&P Biotech Select", "NYSE", "Index", "Biotech", 88),
    ("DJTA", "Dow Jones Transport", "NYSE", "Index", "Transportation", 16200),
    ("DJUA", "Dow Jones Utilities", "NYSE", "Index", "Utilities", 960),
    ("NYA", "NYSE Composite", "NYSE", "Index", "Broad Market", 18200),
    ("W5000", "Wilshire 5000", "NYSE", "Index", "Total Market", 45200),
    ("SP100", "S&P 100", "NYSE", "Index", "Mega Cap", 2400),
    ("SP500GR", "S&P 500 Growth", "NYSE", "Index", "Growth", 3200),
    ("SP500VAL", "S&P 500 Value", "NYSE", "Index", "Value", 1750),
    ("SPXEW", "S&P 500 Equal Weight", "NYSE", "Index", "Equal Weight", 6800),
    ("SP400GR", "S&P MidCap 400 Growth", "NYSE", "Index", "Mid Cap Growth", 1420),
    ("SP600GR", "S&P SmallCap 600 Growth", "NYSE", "Index", "Small Cap Growth", 720),
    ("CRSP", "CRSP US Total Market", "NYSE", "Index", "Total Market", 3400),
    ("MSCIKLD", "MSCI USA Momentum", "NYSE", "Index", "Momentum", 4200),
    ("ARKIDX", "NYSE FANG+", "NYSE", "Index", "Technology", 9800),
    ("IXRE", "NASDAQ Real Estate", "NASDAQ", "Index", "Real Estate", 420),
    ("IXTC", "NASDAQ Telecom", "NASDAQ", "Index", "Telecom", 580),
    ("DEFIDX", "S&P 500 Financials", "NYSE", "Index", "Financial Services", 720),
    ("SP5ENERGY", "S&P 500 Energy", "NYSE", "Index", "Energy", 860),
    ("SP5HEALTH", "S&P 500 Health Care", "NYSE", "Index", "Healthcare", 1650),
    ("SP5INDU", "S&P 500 Industrials", "NYSE", "Index", "Industrials", 1020),
    ("SP5TECH", "S&P 500 Info Tech", "NYSE", "Index", "Technology", 3500),
    ("SP5MATL", "S&P 500 Materials", "NYSE", "Index", "Materials", 540),
    ("SP5CONS", "S&P 500 Consumer Disc", "NYSE", "Index", "Consumer Disc", 1580),
    ("SP5STPL", "S&P 500 Consumer Staples", "NYSE", "Index", "Consumer Staples", 870),
    ("SP5COMM", "S&P 500 Communication", "NYSE", "Index", "Communication", 280),
    ("SP5UTIL", "S&P 500 Utilities", "NYSE", "Index", "Utilities", 380),
    ("SP5REIT", "S&P 500 Real Estate", "NYSE", "Index", "Real Estate", 290),
    ("SPTSX", "S&P/TSX Composite (Canada)", "TSX", "Index", "Broad Market", 22000),
    # European Indices (91-130)
    ("FTSE100", "FTSE 100", "LSE", "Index", "Broad Market", 7800),
    ("DAX", "DAX 40", "XETRA", "Index", "Broad Market", 18200),
    ("CAC40", "CAC 40", "EURONEXT", "Index", "Broad Market", 7600),
    ("IBEX35", "IBEX 35", "BME", "Index", "Broad Market", 10500),
    ("FTSEMIB", "FTSE MIB", "BIT", "Index", "Broad Market", 33500),
    ("AEX", "AEX Index", "EURONEXT", "Index", "Broad Market", 860),
    ("SMI", "Swiss Market Index", "SIX", "Index", "Broad Market", 11800),
    ("BEL20", "BEL 20", "EURONEXT", "Index", "Broad Market", 3850),
    ("OMXS30", "OMX Stockholm 30", "NASDAQ_OMX", "Index", "Broad Market", 2450),
    ("OMXC25", "OMX Copenhagen 25", "NASDAQ_OMX", "Index", "Broad Market", 2800),
    ("OMXH25", "OMX Helsinki 25", "NASDAQ_OMX", "Index", "Broad Market", 4600),
    ("PSI20", "PSI 20", "EURONEXT", "Index", "Broad Market", 6500),
    ("ATX", "Austrian Traded Index", "VSE", "Index", "Broad Market", 3550),
    ("WIG20", "WIG 20", "WSE", "Index", "Broad Market", 2400),
    ("PX", "Prague PX Index", "PSE", "Index", "Broad Market", 1580),
    ("BUX", "Budapest BUX", "BSE_HU", "Index", "Broad Market", 68000),
    ("ISEQ", "ISEQ Overall", "EURONEXT", "Index", "Broad Market", 9200),
    ("OBX", "OBX Index", "OSE", "Index", "Broad Market", 1280),
    ("STOXX50", "Euro Stoxx 50", "STOXX", "Index", "Eurozone Blue Chip", 4950),
    ("STOXX600", "Stoxx Europe 600", "STOXX", "Index", "Pan-European", 510),
    ("STOXX50V", "Euro Stoxx 50 Volatility", "STOXX", "Index", "Volatility", 16.8),
    ("FTSE250", "FTSE 250", "LSE", "Index", "Mid Cap", 20500),
    ("FTSEAIM", "FTSE AIM All-Share", "LSE", "Index", "Small Cap", 780),
    ("MDAX", "MDAX", "XETRA", "Index", "Mid Cap", 26800),
    ("SDAX", "SDAX", "XETRA", "Index", "Small Cap", 14200),
    ("TDAX", "TecDAX", "XETRA", "Index", "Technology", 3400),
    ("CACNEXT20", "CAC Next 20", "EURONEXT", "Index", "Mid Cap", 12800),
    ("CACMID60", "CAC Mid 60", "EURONEXT", "Index", "Mid Cap", 15200),
    ("FTSEALLSHR", "FTSE All-Share", "LSE", "Index", "All Cap", 4350),
    ("SXXP", "Stoxx Europe Total Market", "STOXX", "Index", "Total Market", 490),
    ("MSCIEUROPE", "MSCI Europe", "MSCI", "Index", "Pan-European", 2150),
    ("MSCIEMU", "MSCI EMU", "MSCI", "Index", "Eurozone", 180),
    ("SXXPGR", "Stoxx Europe Growth", "STOXX", "Index", "Growth", 320),
    ("SXXPVAL", "Stoxx Europe Value", "STOXX", "Index", "Value", 210),
    ("SETFS", "SET Financial Services", "STOXX", "Index", "Financial Services", 580),
    ("SETHC", "SET Healthcare", "STOXX", "Index", "Healthcare", 1120),
    ("SETECH", "SET Technology", "STOXX", "Index", "Technology", 850),
    ("SETENG", "SET Energy", "STOXX", "Index", "Energy", 420),
    ("IMOEX", "MOEX Russia Index", "MOEX", "Index", "Broad Market", 3200),
    ("BIST100", "BIST 100 (Turkey)", "BIST", "Index", "Broad Market", 9800),
    # Asian Indices (131-175)
    ("NI225", "Nikkei 225", "TSE", "Index", "Blue Chip", 38500),
    ("TOPIX", "TOPIX", "TSE", "Index", "Broad Market", 2680),
    ("TPX400", "TOPIX 400", "TSE", "Index", "Mid Cap", 1950),
    ("JPXN400", "JPX-Nikkei 400", "TSE", "Index", "Quality", 21500),
    ("MOTHERS", "TSE Growth Market 250", "TSE", "Index", "Growth", 680),
    ("HSI", "Hang Seng Index", "HKSE", "Index", "Blue Chip", 17500),
    ("HSCEI", "Hang Seng China Enterprises", "HKSE", "Index", "China H-Shares", 6200),
    ("HSTECH", "Hang Seng Tech", "HKSE", "Index", "Technology", 4200),
    ("SHCOMP", "Shanghai Composite", "SSE", "Index", "Broad Market", 3150),
    ("SZCOMP", "Shenzhen Composite", "SZSE", "Index", "Broad Market", 1950),
    ("CSI300", "CSI 300", "SSE", "Index", "Broad Market", 3600),
    ("CSI500", "CSI 500", "SSE", "Index", "Mid Cap", 5200),
    ("CSI1000", "CSI 1000", "SSE", "Index", "Small Cap", 6800),
    ("CHINEXT", "ChiNext Index", "SZSE", "Index", "Growth", 1950),
    ("STAR50", "SSE STAR Market 50", "SSE", "Index", "Technology", 980),
    ("KOSPI", "KOSPI", "KRX", "Index", "Broad Market", 2680),
    ("KOSDAQ", "KOSDAQ", "KRX", "Index", "Technology", 880),
    ("KRX100", "KRX 100", "KRX", "Index", "Broad Market", 6800),
    ("TWSE", "TAIEX", "TWSE", "Index", "Broad Market", 20500),
    ("STI", "Straits Times Index", "SGX", "Index", "Broad Market", 3250),
    ("KLCI", "FTSE Bursa Malaysia KLCI", "BURSA", "Index", "Broad Market", 1520),
    ("SETIDX", "SET Index (Thailand)", "SETEX", "Index", "Broad Market", 1350),
    ("JCI", "Jakarta Composite", "IDX", "Index", "Broad Market", 7200),
    ("PSEI", "PSEi Composite", "PSE", "Index", "Broad Market", 6800),
    ("VNINDEX", "VN-Index", "HOSE", "Index", "Broad Market", 1260),
    ("ASX200", "S&P/ASX 200", "ASX", "Index", "Broad Market", 7800),
    ("ASX300", "S&P/ASX 300", "ASX", "Index", "Broad Market", 7750),
    ("AORD", "All Ordinaries", "ASX", "Index", "All Cap", 8050),
    ("AXSML", "S&P/ASX Small Ords", "ASX", "Index", "Small Cap", 3200),
    ("NZX50", "S&P/NZX 50", "NZX", "Index", "Broad Market", 12400),
    ("MSCIASIA", "MSCI AC Asia Pacific", "MSCI", "Index", "Pan-Asian", 178),
    ("MSCIAPXJ", "MSCI Asia ex Japan", "MSCI", "Index", "Asia ex Japan", 580),
    ("MSCIEM", "MSCI Emerging Markets", "MSCI", "Index", "Emerging Markets", 1080),
    ("MSCICHINA", "MSCI China", "MSCI", "Index", "China", 62),
    ("MSCIWORLD", "MSCI World", "MSCI", "Index", "Global Developed", 3400),
    ("MSCIACWI", "MSCI ACWI", "MSCI", "Index", "Global All Country", 780),
    ("MSCIEAFE", "MSCI EAFE", "MSCI", "Index", "Developed ex US", 2300),
    ("MSCIFM", "MSCI Frontier Markets", "MSCI", "Index", "Frontier Markets", 620),
    ("MSCIINDIA", "MSCI India", "MSCI", "Index", "India", 2200),
    ("MSCIJAPAN", "MSCI Japan", "MSCI", "Index", "Japan", 1450),
    ("MSCIKOREA", "MSCI Korea", "MSCI", "Index", "Korea", 520),
    ("MSCITAIWAN", "MSCI Taiwan", "MSCI", "Index", "Taiwan", 640),
    ("MSCIBRAZIL", "MSCI Brazil", "MSCI", "Index", "Brazil", 1800),
    ("MSCISAFR", "MSCI South Africa", "MSCI", "Index", "South Africa", 380),
    ("MSCIMEXICO", "MSCI Mexico", "MSCI", "Index", "Mexico", 4200),
    # Middle East, Africa, Latin America (176-200)
    ("TASI", "Tadawul All Share (Saudi)", "TADAWUL", "Index", "Broad Market", 12200),
    ("DFMGI", "DFM General (Dubai)", "DFM", "Index", "Broad Market", 4200),
    ("ADI", "ADX General (Abu Dhabi)", "ADX", "Index", "Broad Market", 9200),
    ("QSI", "QE Index (Qatar)", "QSE", "Index", "Broad Market", 10500),
    ("KWSE", "Boursa Kuwait All Share", "BK", "Index", "Broad Market", 7200),
    ("BHSE", "Bahrain All Share", "BAX", "Index", "Broad Market", 2050),
    ("MSM30", "MSM 30 (Oman)", "MSM", "Index", "Broad Market", 4700),
    ("TA35", "TA-35 (Israel)", "TASE", "Index", "Broad Market", 1950),
    ("EGX30", "EGX 30 (Egypt)", "EGX", "Index", "Broad Market", 28500),
    ("NGSEASI", "NGX All-Share (Nigeria)", "NGX", "Index", "Broad Market", 98500),
    ("JSE40", "FTSE/JSE Top 40", "JSE", "Index", "Blue Chip", 72500),
    ("NSEASI", "NSE All-Share (Kenya)", "NSEAF", "Index", "Broad Market", 112),
    ("GSECI", "GSE Composite (Ghana)", "GSE", "Index", "Broad Market", 3400),
    ("BOVESPA", "Ibovespa (Brazil)", "B3", "Index", "Broad Market", 128000),
    ("MERVAL", "S&P MERVAL (Argentina)", "BCBA", "Index", "Broad Market", 1450000),
    ("IPSA", "S&P CLX IPSA (Chile)", "BVS", "Index", "Broad Market", 6200),
    ("COLCAP", "MSCI COLCAP (Colombia)", "BVC", "Index", "Broad Market", 1380),
    ("IPC", "S&P/BMV IPC (Mexico)", "BMV", "Index", "Broad Market", 56200),
    ("SPBLPGPT", "S&P/BVL Peru General", "BVL", "Index", "Broad Market", 22500),
    ("BVPSI", "BVPSI (Ecuador)", "BVQ", "Index", "Broad Market", 1680),
    ("FTSEGACS", "FTSE Global All Cap", "FTSE", "Index", "Global Total", 10200),
    ("FTSEDM", "FTSE Developed Markets", "FTSE", "Index", "Developed", 2450),
    ("FTSEEMG", "FTSE Emerging Markets", "FTSE", "Index", "Emerging", 830),
    ("SPDJI", "S&P Global 1200", "S&P_DJI", "Index", "Global", 3400),
    ("SPGLOBAL", "S&P Global 100", "S&P_DJI", "Index", "Global Blue Chip", 2680),
]

start_id = 492
entries = []

for i, (symbol, name, exchange, sector, industry, price) in enumerate(INDICES):
    idx = start_id + i
    pct = round(random.uniform(-3.0, 3.0), 2)
    change = round(price * pct / 100, 2)
    high = round(price * random.uniform(1.05, 1.25), 2)
    low = round(price * random.uniform(0.7, 0.92), 2)
    entry = {
        "id": idx,
        "symbol": symbol,
        "name": name,
        "type": "index",
        "exchange": exchange,
        "sector": sector,
        "industry": industry,
        "market_cap": None,
        "current_price": price,
        "day_change": change,
        "day_change_pct": pct,
        "high_52w": high,
        "low_52w": low,
        "is_active": True
    }
    entries.append(entry)

lines = []
for e in entries:
    parts = []
    for k, v in e.items():
        if isinstance(v, str):
            val = json.dumps(v)
        elif isinstance(v, bool):
            val = str(v)
        elif v is None:
            val = "None"
        else:
            val = str(v)
        parts.append(f'"{k}":{val}')
    lines.append("    {" + ",".join(parts) + "},")

output = "\n".join(lines)
print(f"# Generated {len(entries)} index entries (IDs {start_id}-{start_id+len(entries)-1})")
print(output)
